name: 'Build and publish application'

on:
  push:
    branches:
      - develop
      - main
      - 'release/**'
      - 'feature/**'
      - 'hotfix/**'
      - 'copilot/**'
    paths-ignore:
      - 'README.md'
      - 'docs/*'
      - 'scripts/*'
      - '.vscode/*'
      - 'gh-pages/**'
      - '.github/workflows/deploy-gh-pages.yml'

permissions:
  checks: write
  contents: write
  pull-requests: write
  actions: read

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  NUGET_CERT_REVOCATION_MODE: offline
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  PUBLISH_CODECOV: github.event_name == 'pull_request' || startsWith(github.ref, 'refs/heads/develop') || startsWith(github.ref, 'refs/heads/main')

jobs:

  net-test:
    name: .NET tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [
          ubuntu-latest
          #windows-latest
        ]

    steps:
    - name: Checkout sources
      uses: actions/checkout@v6

    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json

    - name: Restore NuGet packages
      run: dotnet restore --verbosity minimal

    - name: Run .NET tests
      run: dotnet test --coverage --coverage-output-format cobertura --coverage-settings ./test/coverage.config --report-trx --configuration Release --no-progress

    - name: Upload test results
      uses: actions/upload-artifact@v7
      if: matrix.os == 'ubuntu-latest'
      with:
        name: net-test-results
        path: |
          ./**/*.trx
          ./**/*.cobertura.xml

  test-and-coverage-results:
    name: Publish test and coverage results
    runs-on: ubuntu-latest

    needs: [ net-test ]

    steps:
    # While we don't use sources directly in this job the test reporter wants to check
    # some files through git so we need the sources.
    - name: Checkout sources
      uses: actions/checkout@v6

    - name: Download .NET tests results
      uses: actions/download-artifact@v8
      with:
        name: net-test-results
        path: ./

    - name: Create history folder
      run: mkdir ./coverage-history
      working-directory: ./

    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json

    - name: Generate coverage report
      uses: danielpalme/ReportGenerator-GitHub-Action@v5
      with:
        reports: './**/*.cobertura.xml;./**/cobertura-coverage.xml'
        targetdir: 'coverage-report'
        reporttypes: 'MarkdownSummary;Cobertura'
        assemblyfilters: '-xunit*'
        verbosity: 'Info'

    - name: Upload coverage report
      uses: actions/upload-artifact@v7
      with:
        name: coverage-report
        path: coverage-report

    - name: Upload to Codecov
      uses: codecov/codecov-action@v6
      # To save on uploads, only upload coverage from the main branches and PRs
      if: env.PUBLISH_CODECOV
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage-report/Cobertura.xml

  net-build:
    name: .NET build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    needs: [ net-test ]

    strategy:
      matrix:
        os: [
          ubuntu-latest,
          windows-latest,
          macos-latest,
          macos-26-intel]

    steps:
    - name: Checkout sources
      uses: actions/checkout@v6

    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json

    - name: Restore NuGet packages
      run: dotnet restore --verbosity minimal

    - name: Pack NuGet package
      if: matrix.os == 'ubuntu-latest'
      run: dotnet pack --output ./artifacts --configuration Release ./src/Karls.Gitflow.Tool/Karls.Gitflow.Tool.csproj
      working-directory: ./

    - name: Upload packages
      uses: actions/upload-artifact@v7
      if: matrix.os == 'ubuntu-latest'
      with:
        name: packages
        path: ./artifacts/*.nupkg
        if-no-files-found: error

    - name: Publish tool for Windows x64
      if: matrix.os == 'windows-latest'
      run: dotnet publish src/Karls.Gitflow.Tool/Karls.Gitflow.Tool.csproj --configuration Release --runtime win-x64 --self-contained --output ./artifacts/publish-windows --no-restore

    - name: Publish tool for macOS (arm64)
      if: matrix.os == 'macos-latest'
      run: dotnet publish src/Karls.Gitflow.Tool/Karls.Gitflow.Tool.csproj --configuration Release --runtime osx-arm64 --self-contained --output ./artifacts/publish-macos-arm64 --no-restore

    - name: Publish tool for macOS (x64)
      if: matrix.os == 'macos-26-intel'
      run: dotnet publish src/Karls.Gitflow.Tool/Karls.Gitflow.Tool.csproj --configuration Release --runtime osx-x64 --self-contained --output ./artifacts/publish-macos-x64 --no-restore

    - name: Generate checksums
      uses: Solratic/checksum-action@v1
      with:
        pattern: ./artifacts/publish/**/*

    - name: Upload Windows publish artifacts
      uses: actions/upload-artifact@v7
      if: matrix.os == 'windows-latest'
      with:
        name: windows-publish
        path: ./artifacts/publish/windows
        if-no-files-found: error

    - name: Upload macOS publish artifacts
      uses: actions/upload-artifact@v7
      if: matrix.os == 'macos-26-intel'
      with:
        name: macos-x64-publish
        path: ./artifacts/publish-macos-x64
        if-no-files-found: error

    - name: Upload macOS arm64 publish artifacts
      uses: actions/upload-artifact@v7
      if: matrix.os == 'macos-latest'
      with:
        name: macos-arm64-publish
        path: ./artifacts/publish-macos-arm64
        if-no-files-found: error

  windows-installer-build:
    name: Windows installer build
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main'

    needs: [ net-build ]

    steps:
    - name: Checkout sources
      uses: actions/checkout@v6

    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json

    - name: Download Windows publish artifacts
      uses: actions/download-artifact@v8
      with:
        name: windows-publish
        path: ./artifacts/publish/

    - name: Build Windows installer
      run: dotnet build src/Karls.Gitflow.WindowsInstaller/Karls.Gitflow.WindowsInstaller.wixproj --configuration Release "-p:ToolPublishDir=${{ github.workspace }}/artifacts/publish/"

    - name: Upload installer artifact
      uses: actions/upload-artifact@v7
      with:
        name: windows-installer
        path: ./src/Karls.Gitflow.WindowsInstaller/bin/**/*.msi
        if-no-files-found: error

  publish:
    name: NuGet Publish
    needs: net-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      id-token: write

    steps:
    - name: Checkout sources
      uses: actions/checkout@v6
      with:
        sparse-checkout: |
          global.json
        sparse-checkout-cone-mode: false

    - name: Download artifacts
      uses: actions/download-artifact@v8
      with:
        name: packages
        path: ./artifacts/

    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json

    - name: NuGet login (OIDC → temp API key)
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_PROFILE }}

    - name: Publish package to NuGet.org
      run: dotnet nuget push artifacts/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      working-directory: ./
